### ISSUE TITLE
feat: Provision examples with .env file for OPENAIKEY

### ISSUE THREAD

**Issue by dfosco** [callstackincubator/fabrice-ai#106]
Provision examples from `npx create-fabrice-ai` with an `.env` file to hint users where they should add their OPENAI_API_KEY. Ideally this env file could come with entries for different providers as well (assuming they also work out of the box).

![Image](https://github.com/user-attachments/assets/c45baa3f-8c75-405c-b3b3-12b3ec9eab1e)

<img width="951" alt="Image" src="https://github.com/user-attachments/assets/4ff838d6-129a-465b-9421-7771fcb4df81" />

**Comment by pkarw** [comment]
Fixed with: https://github.com/callstackincubator/fabrice-ai/pull/115/files
