### ISSUE TITLE
feat: improve `medical_survey` workflow

### ISSUE THREAD

**Issue by pkarw** [callstackincubator/fabrice-ai#109]
Migrate the changes from closed PR #100 to separate PR - because right now the `resourcePlanner` is not taking the previous answers (tool results) into consideration in planning the next question to be asked.

**Comment by grabbou** [comment]
You mean supervisor? Supervisor plans the next question. Resource Planner just tries to assign it to the best person, in which case, context doesn't matter?

Supervisor already takes into account some context and this PR improves it a bit further: https://github.com/callstackincubator/fabrice-ai/blob/23e6a5e9b4349cb0dee5843357255edb01890cf0/packages/framework/src/agent.ts#L59-L62
